###------------------------------------------------------------------------------------------------------------------------------------
### Config_File_Transmission.yml
###------------------------------------------------------------------------------------------------------------------------------------
# This config yaml file is a ready-made sample of the Authentication and File Transmission steps for your reference and convenience. You can copy and customize the configuration.
# Each line represents a property (key-value pair). 
#   The property key (left side of colon) is a fixed keyword and should not be altered. 
#   The property value (right side of colon) is for user input.    
#   The alignment or spacing for the property key and value should not be changed. It may result in an unexpected error. The YAML file only works with proper alignment.
#   For property values with multiple lines, specify the pipe | character after the property key.  On the following line, indent the lines with values.
# Refer to the sample config file, 'Config_Schema_Migration_ALL_Steps.yml', for the property key help text.
###------------------------------------------------------------------------------------------------------------------------------------

version: 2.0.0

authentication:
  debugMode: false
  hostName: db2b.bmc.com          #specify the mainframe host name or IP address
  port: 32208
  authenticationType: userBased
  user: USER_ID_AUTH
  password: USER_PASS_AUTH
  certificatePath: CERT_PATH_AUTH
  certificatePassword: CERT_PASS_AUTH
  symbolicPropertiesFilePath: symbol_DEJM_BUILD.properties
  debugModeAllSteps: false
  executionIdentifier: PipelineName=PIPELINENAME_VALUE,RunNumber=RUNNUMBER_VALUE,RunBy=RUNBY_VALUE,RunMode=RUNMODE_VALUE
  
fileUpload:
  - stepName: local_to_mainframe
    runStepAlways: false
    debugMode: false
    sourceDirectory: .
    sourceFileName: DDL_FILE_FT_UPLOAD
    destinationPds: $[ddlpds]
    destinationMember: JOB_ID
