###------------------------------------------------------------------------------------------------------------------------------------
### Config_SQL_Assurance_Static_SQL.yml
###------------------------------------------------------------------------------------------------------------------------------------
# This config yaml file is a ready-made sample of the Authentication and Static SQL steps for your reference and convenience. You can copy and customize the configuration.
# Each line represents a property (key-value pair). 
#   The property key (left side of colon) is a fixed keyword and should not be altered. 
#   The property value (right side of colon) is for user input.    
#   The alignment or spacing for the property key and value should not be changed. It may result in an unexpected error. The YAML file only works with proper alignment.
#   For property values with multiple lines, specify the pipe | character after the property key.  On the following line, indent the lines with values.
# Refer to the sample config file, 'Config_SQL_Assurance_ALL_Steps.yml', for the property key help text.
###------------------------------------------------------------------------------------------------------------------------------------

version: 2.0.0

authentication:
  debugMode: true
  hostName: db2b.bmc.com          #specify the mainframe host name or IP address
  port: 32208
  authenticationType: userBased
  user: USER_ID_AUTH
  password: USER_PASS_AUTH
  certificatePath: CERT_PATH_AUTH
  certificatePassword: CERT_PASS_AUTH
  symbolicPropertiesFilePath: AMI_DevOps_SMPE1310_DEJM.properties
  debugModeAllSteps: false
  executionIdentifier: PipelineName=PIPELINENAME_VALUE,RunNumber=RUNNUMBER_VALUE,RunBy=RUNBY_VALUE,RunMode=RUNMODE_VALUE
  
analyzeStaticSql:
  - stepName: static_sql_package
    debugMode: true
    generateJclOnly: false
    ssid: DEJM               #specify Db2 subsystem ID
    violationResponse: warn
    explainMethod: dynamic
    objectType: package
    objectName: ACSBQCO             #specify name of the Package
    collectionIdPackage: RDAJZL   #specify name of the Collection ID
    versionPackage: ACS_1120_BPU7868      #specify name of the package version
    useObjectListFile: false
    objectListContinueOnError: false
    objectListFilePath:
    jobCard: |
      //COBSSQL JOB ($[acctno]),'STATIC-SQL',
      // CLASS=A,MSGLEVEL=(1,1)
      //*
    sqlExplorerInputStream: |
      //PSSMAIN.SYSIN DD * 
      --NEWOBJ 
      OBJECT=PACKAGE 
      NAME="${objectName}"
      COLLID="${collectionIdPackage}"
      VERSION="${versionPackage}" 
      RULES="$[rules]" 
      RULEDSN="$[ruledsn]" 
      PLANTBL="${explainMethod}" 
      CURRENCY="$[currency]" 
      MSGLEVEL=ALL
      --ENDOBJ
    jcl: |
      ${jobCard}
      //*
      // JCLLIB ORDER=($[proclib])
      //*
      //JOBLIB DD DSN=$[joblib1],DISP=SHR
      //       DD DSN=$[joblib2],DISP=SHR
      //       DD DSN=$[dsnexit],DISP=SHR
      //       DD DSN=$[dsnload],DISP=SHR
      //***************************************************
      //*
      // SET RTEHLQ=$[rtehlq]
      // SET USRHLQ=$[usrhlq]
      //*
      // EXPORT SYMLIST=(*)
      //*
      // SET SSID=${ssid}
      // SET PSSPLAN=$[pssplan]
      // SET GUDPLAN=$[gudplan]
      // SET GENDEBUG='${debugMode}'
      // SET LOGMODE='${violationResponse}'
      // SET RULSPACE='SPACE=(CYL,(10,10)),'
      // SET VTIBSZ=20
      //*-----------------------------------------------------------------
      //*
      //SQLXPLOR EXEC COBPRPSS
      ${sqlExplorerInputStream}
      //RULESOUT.SYSUT2 DD &GENDEBUG
      //*-----------------------------------------------------------------
      //*
      //IFPSS    IF (SQLXPLOR.PSSMAIN.RC EQ 4) THEN
      //COBLOGER EXEC COBPRLOG
      //LOGGER.AS$INPUT DD DSN=&&RULESOUT,
      //            DISP=(OLD,DELETE)
      //IFPSSEND ENDIF
      //*
    maxJobWaitTime: 15
