###------------------------------------------------------------------------------------------------------------------------------------
### Workflow_File_Transmission_Sample.yml (for GitHub Actions)
###------------------------------------------------------------------------------------------------------------------------------------
# The sample workflow performs Authentication + File Transmission steps using application defined command step.
# The sample workflow script is defined to use various items like below: 
#  a) References to variables added through GitHub Actions secrets and variables. 
#  b) Use of Linux based sed command to replace input as variable name by variable definition from GitHub Actions secrets and variables.    
#  c) Use of configuration file (Config_File_Transmission.yml), that is maintained in default root folder.
#     Example of properties of authentication step is taken from Config_File_Transmission.yml file: 
#            step authentication Config_File_Transmission.yml
#     Note: If pipeline executes with default configuration file name config.yml, that is maintained in root folder, then file name is not required in step command.
#     Example of properties of authentication step is taken from default file name config.yml maintained in root folder:
#            step authentication
###------------------------------------------------------------------------------------------------------------------------------------
name: <name of the workflow>      #specify workflow name

on:
  workflow_dispatch             #manual trigger of the workflow

jobs:
  File_Transmission:              #name of the job
    runs-on: <name of the runner> #specify runner name
    container: 
      image: <Image location>/devopsuc:13.01.00.0002-GA
      options: -u root
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v3
      
      # For certBased Authentication, uncomment the following task to unzip the specified client certificate
      # from repository into path specified with -d parameter (ex. /opt/secret)  
      - name: unzip client certificate
        run: |
         unzip -P "${{secrets.ZIP_CERT_PW}}" <clientCertificateName>.p12 -d /opt/secret
      
      # Perform various initialization functions using Linux based command sed
      - name: Initialization
        run: |
          echo "Replace variables defined in Config_File_Transmission.yml file"
          # Linux command sed is used to replace the config file variables with GitHub Actions secrets and variables
          sed -i "s/USER_ID_AUTH/${{vars.user_id}}/" Config_File_Transmission.yml
          sed -i "s/USER_PASS_AUTH/${{secrets.user_pass}}/" Config_File_Transmission.yml
          # For certBased Authentication, uncomment the following 2 sed commands
          sed -i "s|CERT_PATH_AUTH|$GITHUB_WORKSPACE/Afrozp12.p12|" Config_File_Transmission.yml
          sed -i "s/CERT_PASS_AUTH/${{secrets.CERT_PASS }}/" Config_File_Transmission.yml
          # Use syntax \<var name\> to find and replace the exact matching word
          sed -i "s/\<JOB_ID\>/${{vars.job_id}}/" Config_File_Transmission.yml
          sed -i "s/DDL_FILE_FT_UPLOAD/${{vars.ddl_file}}/" Config_File_Transmission.yml
          # Use GitHub Actions environment variables to fetch workflow name, run number, run by and run mode of the executing workflow
          sed -i "s/PIPELINENAME_VALUE/${{ github.workflow}}/" Config_File_Transmission.yml
          sed -i "s/RUNNUMBER_VALUE/${{github.run_id}}/" Config_File_Transmission.yml
          sed -i "s/RUNBY_VALUE/${{github.actor}}/" Config_File_Transmission.yml
          sed -i "s/RUNMODE_VALUE/${{github.event_name}}/" Config_File_Transmission.yml         
          echo "-----   Config_File_Transmission.yml file is updated -----"
      
      # Execute application step - authentication
      - name: Authentication 
        run:
          step authentication Config_File_Transmission.yml
          
      # Execute application step - fileUpload (local_to_mainframe)
      - name: File Transmission 
        run:
          step local_to_mainframe Config_File_Transmission.yml
